name: Create Release

on:
  push:
    branches: [ main ]

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version-changed: ${{ steps.version-check.outputs.changed }}
      new-version: ${{ steps.version-check.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Check if version changed
        id: version-check
        run: |
          # Get current version from mix.exs
          CURRENT_VERSION=$(grep 'version:' mix.exs | sed 's/.*version: "\(.*\)".*/\1/')
          echo "Current version: $CURRENT_VERSION"
          
          # Get previous version from mix.exs
          git checkout HEAD~1 -- mix.exs 2>/dev/null || echo "No previous version found"
          PREVIOUS_VERSION=$(grep 'version:' mix.exs | sed 's/.*version: "\(.*\)".*/\1/' 2>/dev/null || echo "0.0.0")
          echo "Previous version: $PREVIOUS_VERSION"
          
          # Restore current mix.exs
          git checkout HEAD -- mix.exs
          
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed from $PREVIOUS_VERSION to $CURRENT_VERSION"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build-and-release:
    needs: check-version
    if: needs.check-version.outputs.version-changed == 'true'
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.1'
          otp-version: '27.1'
      
      - name: Set up Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1
      
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      
      - name: Install dependencies
        run: mix deps.get
      
      - name: Build releases
        run: |
          echo "=== Environment check ==="
          echo "Zig version: $(zig version)"
          echo "Platform: $(uname -a)"
          echo "Current directory: $(pwd)"
          
          echo "=== Running mix release ==="
          MIX_ENV=prod mix release --overwrite 2>&1 | tee build.log
          
          echo "=== Build log analysis ==="
          if grep -i "burrito" build.log; then
            echo "Burrito messages found in build log"
          else
            echo "No Burrito messages in build log - this suggests Burrito didn't run"
          fi
          
          echo "=== Post-build directory check ==="
          echo "Contents of current directory:"
          ls -la
          
          echo "=== Checking for burrito_out ==="
          if [ -d "burrito_out" ]; then
            echo "burrito_out directory exists:"
            ls -la burrito_out/
            file burrito_out/*
          else
            echo "burrito_out directory NOT found"
          fi
          
          echo "=== Checking _build structure ==="
          find _build -name "*focus*" -type f -ls
        env:
          MIX_ENV: prod
      
      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          
          # Debug: Show build structure
          echo "=== Build directory structure ==="
          find _build -name "*focus*" -type f -ls
          
          # Initialize counters
          FOUND_FILES=0
          
          # Try to find Burrito outputs in multiple locations
          burrito_dir=""
          if [ -d "burrito_out" ]; then
            burrito_dir="burrito_out"
            echo "Found burrito outputs in: burrito_out/"
          elif [ -d "_build/prod/rel/focus/burrito_out" ]; then
            burrito_dir="_build/prod/rel/focus/burrito_out" 
            echo "Found burrito outputs in: _build/prod/rel/focus/burrito_out/"
          else
            echo "=== Searching for burrito outputs everywhere ==="
            find . -name "*focus*macos*" -o -name "*focus*linux*" -o -name "*focus*windows*" 2>/dev/null || echo "No burrito-style outputs found"
            echo "ERROR: No burrito outputs found!"
            exit 1
          fi
          
          if [ -n "$burrito_dir" ]; then
            echo "=== Processing Burrito outputs ==="
            
            for burrito_file in "$burrito_dir"/*; do
              if [ -f "$burrito_file" ]; then
                filename=$(basename "$burrito_file")
                
                # Map Burrito output to platform and executable name
                case "$filename" in
                  focus_macos)
                    platform="darwin-x86_64"
                    executable_name="focus"
                    ;;
                  focus_macos_m1)
                    platform="darwin-aarch64"
                    executable_name="focus"
                    ;;
                  focus_linux)
                    platform="linux-x86_64"
                    executable_name="focus"
                    ;;
                  focus_windows.exe)
                    platform="windows-x86_64"
                    executable_name="focus.exe"
                    ;;
                  *)
                    echo "Warning: Unknown Burrito output: $filename"
                    continue
                    ;;
                esac
                
                echo "Processing $filename -> focus-$platform.zip ($executable_name)"
                
                # Create temporary directory
                temp_dir="release-assets/temp-$platform"
                mkdir -p "$temp_dir"
                
                # Copy with correct name
                cp "$burrito_file" "$temp_dir/$executable_name"
                chmod +x "$temp_dir/$executable_name"
                
                # Create zip
                cd "$temp_dir"
                zip "../focus-$platform.zip" "$executable_name"
                cd - > /dev/null
                
                # Clean up
                rm -rf "$temp_dir"
                
                FOUND_FILES=$((FOUND_FILES + 1))
              fi
            done
          fi
          
          
          echo "=== Created $FOUND_FILES platform archives ==="
          echo "=== Final zip files ==="
          ls -la release-assets/*.zip || echo "No zip files created"
          
          # Verify we have the expected 4 files
          expected_files=(
            "release-assets/focus-darwin-x86_64.zip"
            "release-assets/focus-darwin-aarch64.zip" 
            "release-assets/focus-linux-x86_64.zip"
            "release-assets/focus-windows-x86_64.zip"
          )
          
          missing_files=()
          for expected_file in "${expected_files[@]}"; do
            if [ ! -f "$expected_file" ]; then
              missing_files+=("$expected_file")
            fi
          done
          
          if [ ${#missing_files[@]} -gt 0 ]; then
            echo "WARNING: Missing expected files:"
            printf '%s\n' "${missing_files[@]}"
          fi
          
          if [ $FOUND_FILES -eq 0 ]; then
            echo "ERROR: No focus executables found!"
            exit 1
          fi
      
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.check-version.outputs.new-version }}"
          name: "Release v${{ needs.check-version.outputs.new-version }}"
          body: |
            ## Focus v${{ needs.check-version.outputs.new-version }}
            
            A simple command-line focus timer that helps you focus on work.
            
            ### Downloads
            Download and extract the appropriate zip file for your platform:
            - **focus-darwin-x86_64.zip**: For Intel Macs
            - **focus-darwin-aarch64.zip**: For Apple Silicon Macs (M1/M2/M3)
            - **focus-linux-x86_64.zip**: For Linux (64-bit)
            - **focus-windows-x86_64.zip**: For Windows (64-bit)
            
            ### Usage
            
            **macOS:**
            ```bash
            # Extract and make executable
            unzip focus-darwin-*.zip
            chmod +x focus
            # Remove quarantine attribute to bypass security warning
            xattr -d com.apple.quarantine focus
            ./focus [work|break|<minutes>]
            ```
            
            **Linux:**
            ```bash
            # Extract and make executable
            unzip focus-linux-*.zip
            chmod +x focus
            ./focus [work|break|<minutes>]
            ```
            
            **Windows:**
            ```cmd
            # Extract the zip file, then run:
            focus-windows-x86_64.exe [work|break|<minutes>]
            ```
          files: release-assets/*.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}